export const PERMISSIONS = {
    PUBLIC: 'PUBLIC',

  // Dashboard
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',

  // Toilets Module
  VIEW_TOILETS: 'VIEW_TOILETS',
  CREATE_TOILET: 'CREATE_TOILET',
  EDIT_TOILET: 'EDIT_TOILET',
  DELETE_TOILET: 'DELETE_TOILET',

  // Vendor Management
  VIEW_VENDORS: 'VIEW_VENDORS',
  CREATE_VENDOR: 'CREATE_VENDOR',
  EDIT_VENDOR: 'EDIT_VENDOR',
  DELETE_VENDOR: 'DELETE_VENDOR',

  // Feedback Management
  VIEW_FEEDBACK: 'VIEW_FEEDBACK',
  RESPOND_FEEDBACK: 'RESPOND_FEEDBACK',
  DELETE_FEEDBACK: 'DELETE_FEEDBACK',

  // User Management
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  DELETE_USER: 'DELETE_USER',

  // Role Based Access
  VIEW_ROLES: 'VIEW_ROLES',
  CREATE_ROLE: 'CREATE_ROLE',
  EDIT_ROLE: 'EDIT_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',

  // Support
  VIEW_SUPPORT: 'VIEW_SUPPORT',

  // Billing (future SaaS monetization)
  VIEW_BILLING: 'VIEW_BILLING',
  MANAGE_SUBSCRIPTION: 'MANAGE_SUBSCRIPTION',
};
