export const TableData={
  "Message": null,
  "IsSuccessful": true,
  "Data": [
    { "Name": "User 1", "UserName": "user1", "TotalSurveyCount": 340 },
    { "Name": "User 2", "UserName": "user2", "TotalSurveyCount": 329 },
    { "Name": "User 3", "UserName": "user3", "TotalSurveyCount": 154 },
    { "Name": "User 4", "UserName": "user4", "TotalSurveyCount": 148 },
    { "Name": "User 5", "UserName": "user5", "TotalSurveyCount": 87 },
    { "Name": "User 6", "UserName": "user6", "TotalSurveyCount": 56 },
    { "Name": "User 7", "UserName": "user7", "TotalSurveyCount": 8 },
    { "Name": "User 8", "UserName": "user8", "TotalSurveyCount": 8 },
    { "Name": "User 9", "UserName": "user9", "TotalSurveyCount": 5 },
    { "Name": "User 10", "UserName": "user10", "TotalSurveyCount": 5 },

    { "Name": "User 11", "UserName": "user11", "TotalSurveyCount": 4 },
    { "Name": "User 12", "UserName": "user12", "TotalSurveyCount": 4 },
    { "Name": "User 13", "UserName": "user13", "TotalSurveyCount": 4 },
    { "Name": "User 14", "UserName": "user14", "TotalSurveyCount": 2 },
    { "Name": "User 15", "UserName": "user15", "TotalSurveyCount": 2 },
    { "Name": "User 16", "UserName": "user16", "TotalSurveyCount": 2 },
    { "Name": "User 17", "UserName": "user17", "TotalSurveyCount": 1 },
    { "Name": "User 18", "UserName": "user18", "TotalSurveyCount": 1 },
    { "Name": "User 19", "UserName": "user19", "TotalSurveyCount": 0 },
    { "Name": "User 20", "UserName": "user20", "TotalSurveyCount": 0 },

    { "Name": "User 21", "UserName": "user21", "TotalSurveyCount": 12 },
    { "Name": "User 22", "UserName": "user22", "TotalSurveyCount": 18 },
    { "Name": "User 23", "UserName": "user23", "TotalSurveyCount": 23 },
    { "Name": "User 24", "UserName": "user24", "TotalSurveyCount": 31 },
    { "Name": "User 25", "UserName": "user25", "TotalSurveyCount": 9 },
    { "Name": "User 26", "UserName": "user26", "TotalSurveyCount": 7 },
    { "Name": "User 27", "UserName": "user27", "TotalSurveyCount": 13 },
    { "Name": "User 28", "UserName": "user28", "TotalSurveyCount": 6 },
    { "Name": "User 29", "UserName": "user29", "TotalSurveyCount": 19 },
    { "Name": "User 30", "UserName": "user30", "TotalSurveyCount": 4 },

    { "Name": "User 31", "UserName": "user31", "TotalSurveyCount": 10 },
    { "Name": "User 32", "UserName": "user32", "TotalSurveyCount": 15 },
    { "Name": "User 33", "UserName": "user33", "TotalSurveyCount": 21 },
    { "Name": "User 34", "UserName": "user34", "TotalSurveyCount": 3 },
    { "Name": "User 35", "UserName": "user35", "TotalSurveyCount": 8 },
    { "Name": "User 36", "UserName": "user36", "TotalSurveyCount": 11 },
    { "Name": "User 37", "UserName": "user37", "TotalSurveyCount": 17 },
    { "Name": "User 38", "UserName": "user38", "TotalSurveyCount": 5 },
    { "Name": "User 39", "UserName": "user39", "TotalSurveyCount": 2 },
    { "Name": "User 40", "UserName": "user40", "TotalSurveyCount": 6 },

    { "Name": "User 41", "UserName": "user41", "TotalSurveyCount": 8 },
    { "Name": "User 42", "UserName": "user42", "TotalSurveyCount": 9 },
    { "Name": "User 43", "UserName": "user43", "TotalSurveyCount": 14 },
    { "Name": "User 44", "UserName": "user44", "TotalSurveyCount": 22 },
    { "Name": "User 45", "UserName": "user45", "TotalSurveyCount": 1 },
    { "Name": "User 46", "UserName": "user46", "TotalSurveyCount": 4 },
    { "Name": "User 47", "UserName": "user47", "TotalSurveyCount": 7 },
    { "Name": "User 48", "UserName": "user48", "TotalSurveyCount": 5 },
    { "Name": "User 49", "UserName": "user49", "TotalSurveyCount": 3 },
    { "Name": "User 50", "UserName": "user50", "TotalSurveyCount": 6 },

    { "Name": "User 51", "UserName": "user51", "TotalSurveyCount": 13 },
    { "Name": "User 52", "UserName": "user52", "TotalSurveyCount": 18 },
    { "Name": "User 53", "UserName": "user53", "TotalSurveyCount": 25 },
    { "Name": "User 54", "UserName": "user54", "TotalSurveyCount": 7 },
    { "Name": "User 55", "UserName": "user55", "TotalSurveyCount": 2 },
    { "Name": "User 56", "UserName": "user56", "TotalSurveyCount": 4 },
    { "Name": "User 57", "UserName": "user57", "TotalSurveyCount": 3 },
    { "Name": "User 58", "UserName": "user58", "TotalSurveyCount": 6 },
    { "Name": "User 59", "UserName": "user59", "TotalSurveyCount": 12 },
    { "Name": "User 60", "UserName": "user60", "TotalSurveyCount": 9 }
  ]
}